server:
  port: 0000
  servlet:
    context-path: /apitermo

spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pgsql.dominio.com.br:porta/banco
    username: usuario
    password: senha
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto API Termo 2
