server:
    port: 8080
    servlet:
        context-path: /apitermo

spring:
    datasource:
        drive-class-name: org.postgresql.Driver
        url: jdbc:postgresql://wlsoftware.cxz4l2dm7mig.sa-east-1.rds.amazonaws.com/coi
        username: postgres
        password: '*Wl131211wl'
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: none

application:
    description: Projeto API Termo 3

#    acessar no browser
#    http://localhost:8080/apitermo/swagger-ui.html
